name: fortune_cat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cats/cat_body_1.png
    - assets/images/cats/cat_body_2.png
    - assets/images/cats/cat_body_3.png
    - assets/images/cats/cat_body_4.png

    - assets/images/accessories/glasses/glasses_1.png
    - assets/images/accessories/glasses/glasses_2.png

    - assets/images/accessories/hats/hat_1.png

    - assets/images/accessories/paws/paws_1.png
    - assets/images/accessories/paws/paws_2.png
    - assets/images/accessories/paws/paws_3.png
    
    - assets/images/accessories/ties/bowtie_1.png