name: fortune_cat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.1.1
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cats/
    - assets/images/backgrounds/accents/
    - assets/images/backgrounds/main/
    - assets/images/accessories/eyes/
    - assets/images/accessories/head/
    - assets/images/accessories/paws/
    - assets/vectors/decor/
    - assets/vectors/icons/
    - assets/vectors/text/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700